# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        maven: [3.3.1, 3.5.4, 3.6.3, 3.8.7, 3.9.0]
        jdk: ["11"]
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif
    if: github.repository == 'mojo-executor/mojo-executor' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
          java-version: ${{ matrix.jdk }}
          distribution: "temurin"
          cache: 'maven'
    - name: Set up Maven
      run:
          mvn --errors --batch-mode --show-version org.apache.maven.plugins:maven-wrapper-plugin:3.1.0:wrapper "-Dmaven=${{ matrix.maven }}"              
    - name: Build with Maven
      run: ./mvnw -B -V install
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   if: ${{ failure() }}
    - name: Codecov
      uses: codecov/codecov-action@v1

  snapshot:
    if: github.repository == 'mojo-executor/mojo-executor' && github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: "temurin"
        cache: 'maven'        
    # https://github.com/marketplace/actions/maven-setings-action
    - name: Maven Settings
      uses: s4u/maven-settings-action@v2
      with:
        sonatypeSnapshots: true
        githubServer: false
        servers: |
            [{
                "id": "sonatype-nexus-snapshots",
                "username": "${{ secrets.SONATYPE_USERNAME }}",
                "password": "${{ secrets.SONATYPE_PASSWORD }}"
            }]
    - name: Deploy Snapshot
      run: mvn -B -V -Dmaven.deploy.skip=releases org.apache.maven.plugins:maven-source-plugin:jar-no-fork deploy
    - name: Codecov
      uses: codecov/codecov-action@v1
